# Create a 'student' dataframe (NA for ungraded assignments)
grades <- data.frame(
  Student = "Your Name",
  `Getting.to.Know.You.Survey` = 5,
  `Terminus.Scavenger.Hunt` = 5,
  `Week.2.Discussion` = 2.5,
  `Week.3.Discussion` = 2.5,
  `Week.4.Discussion` = 2.5,
  `Week.5.Discussion` = 2.5,
  `Week.6.Discussion` = NA,
  `Week.7.Discussion` = NA,
  `Week.8.Discussion` = NA,
  `Week.9.Discussion` = NA,
  `Week.10.Discussion` = NA,
  `Week.2.3.Reflection` = 2.5,
  `Week.3.4.Reflection` = 2.5,
  `Week.4.5.Reflection` = 2.5,
  `Week.5.6.Reflection` = NA,
  `Week.6.7.Reflection` = NA,
  `Week.7.8.Reflection` = NA,
  `Week.8.9.Reflection` = NA,
  `Week.9.10.Reflection` = NA,
  `Exit.Pre.Spring.Survey` = NA,
  `Upload.Spring.Class.Schedule` = NA,
  `hw01_Command.Line.and.Git` = 10,
  `hw02_Intro.to.Programming` = 10,
  `hw03_Control.Structures` = 10,
  `hw04_File.Operations` = NA,
  `hw05_Data.Structures` = NA,
  `hw06_Data.Visualizations` = NA,
  `hw07_Web.Scraping` = NA,
  `hw08_Work.With.Text` = NA,
  `Midterm.Exam` = NA,
  `Final.Exam` = NA
)
